version: '2'
services:
  php:
    volumes:
      - ./app:/home/www-data:ro
    links:
      - ftp
  ftp:
    build: ./build/ftp
    volumes:
      - ./var/data:/data/z01/pastdata:ro
    privileged: true