version: '2'
services:
  php:
    build: ./build/php
    volumes:
      - ./app:/home/www-data:ro
      - ./var/yaf.ini:/usr/local/etc/php/conf.d/yaf.ini:ro
    links:
      - ftp
  ftp:
    build: ./build/ftp
    volumes:
      - ./var/data:/data/z01/pastdata:ro
    privileged: true