version: '2'
services:
  php:
    build: ./build/php
    volumes:
      - ./var/database:/var/lib/cjw
      - ./var/log:/var/log/cjw
      - ./var/application.ini:/home/www-data/conf/application.ini